### ISSUE TITLE
Optimize to get level 8 app

### ISSUE THREAD

**Issue by Limezy** [YunoHost-Apps/homeassistant_ynh#302]
Hi ! Looks like this app is very close to be level 8 ready.
Apparently the blocking point is coming from your configuration files that are embedded into a folder.
Is there any technical reason for that ?
If not, I could help tweaking slightly the scripts to get level 8.
Thanks for the app anyway !

**Comment by ewilly** [comment]
It was level 8 since 2022 and suddenly go back back to level 6 due to a change in linter that produce an error when finding a directory in the conf dir instead of files. I can't see the point behind that (and no point in documentation too), i suspect a false positive and so a technical issue on the linter script side.

**Comment by ewilly** [comment]
issue create on linter side [https://github.com/YunoHost/package_linter/issues/138](https://github.com/YunoHost/package_linter/issues/138)

**Comment by ewilly** [comment]
Linter fixed with [https://github.com/YunoHost/package_linter/pull/141](https://github.com/YunoHost/package_linter/pull/141)
