### ISSUE TITLE
Upgrade fails, then restore fails after Bookworm migration

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/homeassistant_ynh#360]
Failed upgrade log: https://paste.yunohost.org/raw/ewawuxaqow

Failed subsequent restore: https://paste.yunohost.org/raw/kopagicuma

**Comment by ewilly** [comment]
Coule you try testing branche with --force ?

Le 1 août 2024 06:57:09 GMT+02:00, tituspijean ***@***.***> a écrit :

**Comment by tituspijean** [comment]
I have patched the script in my backup, but it still cannot restore due to the following error:

```
Info: [###########++.......] > Updating the pyhton link in the pyhton virtual environment...
Warning: head: cannot open '/var/www/homeassistant/bin/hass' for reading: No such file or directory
```

**Comment by ewilly** [comment]
hum really strange because that's the main executable of homeassistant...
did homeassitant works after you migration and before updating it ?
something went wrong not sure if it's due to the migration process i didn't try it for now and will be away for next weeks.
better is to reinstall (all you configuration is on the data dir which should survive when removing app but perhaps make a backup of ` /home/yunohost.app/homeassistant`).

**Comment by tituspijean** [comment]
I was able to do some black magic (manually reinstall hass), the testing branch upgrade does not fail. :)
